// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlzcruyaxfrlpyajldkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1semNydXlheGZybHB5YWpsZGtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Njg2NDMsImV4cCI6MjA3MTI0NDY0M30.RHygKuaVXH-OUmB_1bJj6t0dmRv48i3Was9LVQCrfW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});